export const usersmock = [
    {
        "id": 1,
        "username": "Admin",
        "fullName": "Le admin",
        "cpf": null,
        "email": "admin@admin.com",
        "avatarPieces": null,
        "confirmed": true,
        "blocked": false,
        "title": null,
        "role": "Admin"
      },
      {
        "id": 131,
        "username": "slkfdgmnlksndg",
        "fullName": "glutose",
        "cpf": "871.637.330-89",
        "email": "gluetose@teste.com",
        "avatarPieces": "body 01,#FFF9C4;hair 02,#F5E99E;face 03,#FFFFFF;shirt 04,#FFFFFF;prop 03,#00838F",
        "confirmed": true,
        "blocked": false,
        "title": "title:01",
        "role": "Manager",
        "business": "M DIAS BRANCO S.A. INDUSTRIA E COMERCIO DE ALIMENTOS"
      },
      {
        "id": 124,
        "username": "Dennis Cardoso",
        "fullName": "Dennis CARDOSO",
        "cpf": "025.193.653-82",
        "email": "dennis@fiec.com",
        "avatarPieces": "body 01,#FFF9C4;hair 01,#FBC02D;face 04,#FFFFFF;shirt 04,#FFFFFF;prop 07,#F5E99E",
        "confirmed": true,
        "blocked": false,
        "title": "title:11",
        "role": "Manager",
        "business": "CLINICA NORDESTE SAUDE LTDA"
      },
      {
        "id": 123,
        "username": "Teste 5",
        "fullName": "user5",
        "cpf": "125.794.790-74",
        "email": "user5@teste.com",
        "avatarPieces": "body 01,#E57373;hair 03,#F5E99E;face 06,#FFFFFF;shirt 03,#FFFFFF;prop 06,#98EAEB",
        "confirmed": true,
        "blocked": false,
        "title": "title:01",
        "role": "Manager",
        "business": "INHOUSE SOLUCOES INTELIGENTES EM AUTOMACAO LTDA"
      },
      {
        "id": 130,
        "username": "çlkmçflhm",
        "fullName": "laktose",
        "cpf": "424.767.070-07",
        "email": "laktose@teste.com",
        "avatarPieces": "body 03,#FFF9C4;hair 06,#F5E99E;face 05,#FFFFFF;shirt 06,#FFFFFF;prop 05,#E57373",
        "confirmed": true,
        "blocked": false,
        "title": "title:01",
        "role": "Manager",
        "business": "NESTLE BRASIL LTDA."
      },
      {
        "id": 129,
        "username": "Teste Build 0.6.2",
        "fullName": "latency",
        "cpf": "802.274.140-04",
        "email": "lat@ncy.com",
        "avatarPieces": "",
        "confirmed": true,
        "blocked": false,
        "title": "title:01",
        "role": "Manager",
        "business": "GOOGLE INTERNATIONAL LLC"
      },
      {
        "id": 119,
        "username": "user4",
        "fullName": "user2",
        "cpf": "90619208090",
        "email": "user4@teste.com",
        "avatarPieces": "",
        "confirmed": true,
        "blocked": false,
        "title": "title:01",
        "role": "Manager",
        "business": "O Banco Bradesco S.A,"
      },
      {
        "id": 118,
        "username": "user1",
        "fullName": "user1",
        "cpf": "90619208090",
        "email": "user1@teste.com",
        "avatarPieces": "",
        "confirmed": true,
        "blocked": false,
        "title": "title:01",
        "role": "Manager",
        "business": "Loja Magic Raiz"
      },
      {
        "id": 120,
        "username": "User 3",
        "fullName": "user3",
        "cpf": "060.076.913-57",
        "email": "user3@teste.com",
        "avatarPieces": "body 01,#FFF9C4;hair 03,#E57373;face 06,#FFFFFF;shirt 03,#FFFFFF;prop 05,#00838F",
        "confirmed": true,
        "blocked": false,
        "title": "title:01",
        "role": "Manager",
        "business": "BUGABOO STUDIO MIDIA INTERATIVA E TREINAMENTO LTDA"
      },
      {
        "id": 127,
        "username": "Nathalia",
        "fullName": "Nathalia Duarte",
        "cpf": "019.645.163-90",
        "email": "t_ndfernandes@sfiec.org.br",
        "avatarPieces": "body 01,#FFEBEE;hair 06,#FBC02D;face 01,#FFFFFF;shirt 06,#FFFFFF;prop 04,#00838F",
        "confirmed": true,
        "blocked": false,
        "title": "title:01",
        "role": "Manager",
        "business": "NATHALIA DUARTE FERNANDES 01964516390"
      },
      {
        "id": 122,
        "username": "user4",
        "fullName": "user4",
        "cpf": null,
        "email": "user4@teste.com",
        "avatarPieces": null,
        "confirmed": false,
        "blocked": false,
        "title": null,
        "role": "Manager"
      },
      {
        "id": 128,
        "username": "jureg",
        "fullName": "some",
        "cpf": "291.211.840-97",
        "email": "some@body.com",
        "avatarPieces": "body 01,#FFF9C4;hair 02,#F5E99E;face 03,#FFFFFF;shirt 03,#FFFFFF;prop 06,#F5E99E",
        "confirmed": true,
        "blocked": false,
        "title": "title:01",
        "role": "Manager",
        "business": "BLAZE COMERCIO EXTERIOR LTDA"
      },
      {
        "id": 132,
        "username": "lkçsdmgmsdfg",
        "fullName": "serotonin",
        "cpf": "871.637.330-89",
        "email": "serotonin@teste.com",
        "avatarPieces": "body 01,#FFF9C4;hair 03,#F5E99E;face 03,#FFFFFF;shirt 03,#FFFFFF;prop 06,#98EAEB",
        "confirmed": true,
        "blocked": false,
        "title": "title:01",
        "role": "Manager",
        "business": "Guarana Wiilson"
      },
      {
        "id": 133,
        "username": "rivotril",
        "fullName": "rivotril",
        "cpf": null,
        "email": "rivotril@teste.com",
        "avatarPieces": null,
        "confirmed": false,
        "blocked": false,
        "title": null,
        "role": "Manager"
      }
    ,
    
      {
        "id": 126,
        "username": "Guilherme ",
        "fullName": "Guilherme ",
        "cpf": null,
        "email": "gmaraujo@sfiec.org.br",
        "avatarPieces": null,
        "confirmed": false,
        "blocked": false,
        "title": null,
        "role": "Employer",
        "business": "CLINICA NORDESTE SAUDE LTDA"
      },
      {
        "id": 125,
        "username": "Dennis",
        "fullName": "Dennis",
        "cpf": "025.193.653-82",
        "email": "dscardoso@sfiec.org.br",
        "avatarPieces": "body 01,#FFF9C4;hair 02,#F5E99E;face 02,#FFFFFF;shirt 04,#FFFFFF;prop 01,#F5E99E",
        "confirmed": true,
        "blocked": false,
        "title": "title:01",
        "role": "Employer",
        "business": "CLINICA NORDESTE SAUDE LTDA"
      },
      {
        "id": 121,
        "username": "Elson",
        "fullName": "Elson",
        "cpf": null,
        "email": "elson@bugaboostudio.com",
        "avatarPieces": null,
        "confirmed": false,
        "blocked": false,
        "title": null,
        "role": "Employer",
        "business": "BUGABOO STUDIO MIDIA INTERATIVA E TREINAMENTO LTDA"
      }

]